# Generated by Django 4.2.6 on 2023-10-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=9)),
                ('direccion', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo_cliente', models.CharField(max_length=100)),
                ('tipo_cliente', models.CharField(max_length=50)),
                ('descripcion_tipo_cliente', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Plancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo_plancha', models.CharField(max_length=100)),
                ('largo', models.DecimalField(decimal_places=0, max_digits=4)),
                ('ancho', models.DecimalField(decimal_places=0, max_digits=4)),
                ('alto', models.DecimalField(decimal_places=0, max_digits=4)),
                ('area', models.DecimalField(decimal_places=0, max_digits=4)),
                ('cod_carton', models.CharField(max_length=5)),
                ('descripcion_cod_carton', models.CharField(max_length=50)),
                ('precio_proveedor', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=255)),
                ('nombre_persona', models.CharField(max_length=40)),
                ('contrasenia', models.CharField(max_length=16)),
                ('token', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cotizacion', models.CharField(max_length=100)),
                ('largo', models.DecimalField(decimal_places=0, max_digits=4)),
                ('ancho', models.DecimalField(decimal_places=0, max_digits=4)),
                ('alto', models.DecimalField(decimal_places=0, max_digits=4)),
                ('cantidad_caja', models.DecimalField(decimal_places=0, max_digits=4)),
                ('cod_carton', models.CharField(max_length=5)),
                ('comentario', models.CharField(max_length=400)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calculo_Cotizaciones.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Cotizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_detalle_cotizacion', models.CharField(max_length=100)),
                ('largo', models.DecimalField(decimal_places=0, max_digits=4)),
                ('ancho', models.DecimalField(decimal_places=0, max_digits=4)),
                ('alto', models.DecimalField(decimal_places=0, max_digits=4)),
                ('comentario', models.CharField(max_length=400)),
                ('cod_estado', models.DecimalField(decimal_places=0, max_digits=3)),
                ('descripcion_estado', models.CharField(max_length=50)),
                ('precio_cotizacion', models.DecimalField(decimal_places=0, max_digits=9)),
                ('excedente', models.DecimalField(decimal_places=0, max_digits=4)),
                ('cantidad_plancha', models.DecimalField(decimal_places=0, max_digits=4)),
                ('cantidad_caja', models.DecimalField(decimal_places=0, max_digits=4)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calculo_Cotizaciones.cliente')),
                ('id_solicitud_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calculo_Cotizaciones.solicitud_cotizacion')),
                ('id_tipo_plancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calculo_Cotizaciones.tipo_plancha')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calculo_Cotizaciones.tipo_cliente'),
        ),
    ]
