# Generated by Django 4.2.6 on 2023-10-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='detalle_cotizaciones',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solicitud_cotizacion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tipo_cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tipo_plancha',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detalle_cotizaciones',
            name='id_detalle_cotizacion',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='id_cotizacion',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_cliente',
            name='id_tipo_cliente',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_plancha',
            name='id_tipo_plancha',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
        migrations.AlterModelTable(
            name='detalle_cotizaciones',
            table='Detalle_Cotizaciones',
        ),
        migrations.AlterModelTable(
            name='solicitud_cotizacion',
            table='Solicitud_Cotizacion',
        ),
        migrations.AlterModelTable(
            name='tipo_cliente',
            table='Tipo_Cliente',
        ),
        migrations.AlterModelTable(
            name='tipo_plancha',
            table='Tipo_Plancha',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
