# Generated by Django 4.2.6 on 2023-11-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0005_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalle_cotizaciones',
            name='alto',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='detalle_cotizaciones',
            name='ancho',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='detalle_cotizaciones',
            name='cantidad_caja',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='detalle_cotizaciones',
            name='cantidad_plancha',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='detalle_cotizaciones',
            name='cod_estado',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='detalle_cotizaciones',
            name='excedente',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='detalle_cotizaciones',
            name='largo',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='detalle_cotizaciones',
            name='precio_cotizacion',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='ancho_maximo',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='excedente_horizontal',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='excedente_vertical',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='id_parametro',
            field=models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='largo_maximo',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='alto',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='ancho',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='cantidad_caja',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='largo',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='tipo_plancha',
            name='ancho',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='tipo_plancha',
            name='area',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='tipo_plancha',
            name='largo',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='tipo_plancha',
            name='precio_proveedor',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
