# Generated by Django 4.2.5 on 2023-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0007_alter_tipo_plancha_ancho_alter_tipo_plancha_largo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_plancha',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
