# Generated by Django 4.2.6 on 2023-11-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0012_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut_cliente_temporal',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
