# Generated by Django 4.2.6 on 2023-11-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0013_cliente_rut_cliente_temporal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id_cliente',
            new_name='rut_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rut_cliente_temporal',
        ),
    ]
