# Generated by Django 4.2.6 on 2023-11-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0014_rename_id_cliente_cliente_rut_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_tipo_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
