# Generated by Django 4.2.6 on 2023-11-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0015_remove_cliente_contrasenia_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_cotizaciones',
            old_name='id_cliente',
            new_name='rut_cliente',
        ),
        migrations.RenameField(
            model_name='solicitud_cotizacion',
            old_name='id_cliente',
            new_name='rut_cliente',
        ),
    ]
