# Generated by Django 4.2.6 on 2023-11-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0016_rename_id_cliente_detalle_cotizaciones_rut_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_cotizacion',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
            preserve_default=False,
        ),
    ]
