# Generated by Django 4.2.6 on 2023-11-16 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0017_solicitud_cotizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_cotizacion',
            name='fecha_cotizacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
