# Generated by Django 4.2.1 on 2023-11-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0019_solicitud_cotizacion_monto_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='nombre de usuario')),
                ('email', models.EmailField(max_length=258, unique=True, verbose_name='correo electronico')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=30, verbose_name='apellidos')),
                ('es_activo', models.BooleanField(default=True)),
                ('es_staff', models.BooleanField(default=False)),
                ('perfil', models.CharField(default='ventas', max_length=20, verbose_name='perfil')),
                ('token', models.CharField(default='95f397a7bce2f2ffbe6c404caa1994ae991c4ee5', max_length=100, verbose_name='token del usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
