# Generated by Django 4.2.6 on 2023-11-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0020_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='monto_total',
            field=models.IntegerField(),
        ),
    ]
