# Generated by Django 4.2.1 on 2023-11-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0020_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
