# Generated by Django 4.2.6 on 2023-11-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0021_delete_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
