# Generated by Django 4.2.1 on 2023-10-28 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_privatedata_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='colicitud_cotizacion',
            fields=[
                ('id_cotizacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_carton', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=200)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='PrivateData',
        ),
    ]
