# Generated by Django 4.2.1 on 2023-10-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_colicitud_cotizacion_delete_privatedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='colicitud_cotizacion',
            new_name='solicitud_cotizacion',
        ),
    ]
