# Generated by Django 4.2.1 on 2023-10-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_colicitud_cotizacion_solicitud_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='alto',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='ancho',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='cantidad_caja',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='cod_carton',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='comentario',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='id_cliente',
            field=models.IntegerField(max_length=int),
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='id_cotizacion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud_cotizacion',
            name='largo',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
