# Generated by Django 4.2.6 on 2023-11-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id_parametro', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False)),
                ('largo_maximo', models.DecimalField(decimal_places=0, max_digits=5)),
                ('ancho_maximo', models.DecimalField(decimal_places=0, max_digits=5)),
                ('excedente_horizontal', models.DecimalField(decimal_places=0, max_digits=5)),
                ('excedente_vertical', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
            options={
                'db_table': 'Parametro',
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
