# Generated by Django 4.2.6 on 2023-11-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0002_parametro_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_plancha',
            name='alto',
        ),
    ]
