# Generated by Django 4.2.6 on 2023-11-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0003_remove_tipo_plancha_alto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_plancha',
            name='descripcion_cod_carton',
        ),
    ]
