# Generated by Django 4.2.6 on 2023-11-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0006_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_plancha',
            name='ancho',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipo_plancha',
            name='largo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
