# Generated by Django 4.2.6 on 2023-11-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculo_Cotizaciones', '0011_alter_tipo_plancha_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False)),
                ('rut_cliente', models.CharField(max_length=12)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('fecha_cotizacion', models.DateTimeField()),
                ('estado_cotizacion', models.CharField(max_length=20)),
                ('cantidad_cajas', models.DecimalField(decimal_places=0, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'Historial',
            },
        ),
    ]
